### ISSUE TITLE
"Failed to read mod version"

### ISSUE THREAD

**Issue by tcmal** [FiskFille/TransformersMod#126]
Crash Log:

```
[16:56:40] [Thread-5/INFO] [STDERR]: [fiskfille.tf.web.update.UpdateChecker:run:36]: [Transformers Mod] Failed to read mod version! Please report this on the GitHub issue tracker! https://github.com/FiskFille/TransformersMod/issues
[16:56:40] [Thread-5/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Invalid version format
[16:56:40] [Thread-5/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at fiskfille.tf.web.update.Version.<init>(Version.java:17)
[16:56:40] [Thread-5/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at fiskfille.tf.web.update.UpdateChecker.run(UpdateChecker.java:22)
```

Forge 1.7.10-10.13.4.1490

**Comment by Gegy** [comment]
Do you have an internet connection?

**Comment by tcmal** [comment]
Yep.

**Comment by tcmal** [comment]
This doesn't actually prevent startup.

**Comment by FiskFille** [comment]
Check in the Forge mod list, what does the version tag for the mod say?

**Comment by tcmal** [comment]
Sorry, I'm not getting this issue anymore.
