### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by Pisces-273** [FiskFille/TransformersMod#127]
Here's the report:

---- Minecraft Crash Report ----
// My bad.

Time: 8/2/15 7:40 PM
Description: Initializing game

java.lang.RuntimeException: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-13,5,] already has the context current
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:497)
    at cpw.mods.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:404)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:574)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-13,5,] already has the context current
    at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
    at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:189)
    at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:110)
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:489)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:497)
    at cpw.mods.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:404)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:574)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10.4
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 123984216 bytes (118 MB) / 251617280 bytes (239 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.3.1408} [Minecraft Forge](forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    transformers{${version}} [Transformers Mod](Transformers-1.7.10-0.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Launched Version: 1.7.10-Forge10.13.3.1408-1.7.10
    LWJGL: 2.9.1
    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Dome SoundPack]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by FiskFille** [comment]
Try uninstalling the Transformers mod - does that fix your problem? If not, it's not a problem with the Transformers mod.
