### ISSUE TITLE
My game crashes when I try to create a world and yes I have reinstalled it again and agian

### ISSUE THREAD

**Issue by DeadAtNooN** [FiskFille/TransformersMod#141]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 10/6/15 11:11 PM
Description: Unexpected error

java.lang.ClassCastException: fiskfille.tf.model.ModelBipedTF cannot be cast to api.player.model.ModelPlayer
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.createModel(SmartRenderRenderPlayerBase.java:30)
    at net.smart.render.SmartRenderRender.<init>(SmartRenderRender.java:21)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.getRenderRender(SmartRenderRenderPlayerBase.java:24)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.renderFirstPersonArm(SmartRenderRenderPlayerBase.java:57)
    at api.player.render.RenderPlayerAPI.renderFirstPersonArm(RenderPlayerAPI.java:2416)
    at api.player.render.RenderPlayerAPI.renderFirstPersonArm(RenderPlayerAPI.java:2404)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_82441_a(RenderPlayer.java)
    at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531)
    at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
    at fiskfille.tf.render.entity.EntityRendererAlt.func_78471_a(EntityRendererAlt.java:35)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at fiskfille.tf.render.entity.EntityRendererAlt.func_78480_b(EntityRendererAlt.java:67)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.createModel(SmartRenderRenderPlayerBase.java:30)
    at net.smart.render.SmartRenderRender.<init>(SmartRenderRender.java:21)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.getRenderRender(SmartRenderRenderPlayerBase.java:24)
    at net.smart.render.playerapi.SmartRenderRenderPlayerBase.renderFirstPersonArm(SmartRenderRenderPlayerBase.java:57)
    at api.player.render.RenderPlayerAPI.renderFirstPersonArm(RenderPlayerAPI.java:2416)
    at api.player.render.RenderPlayerAPI.renderFirstPersonArm(RenderPlayerAPI.java:2404)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_82441_a(RenderPlayer.java)
    at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531)
    at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
    at fiskfille.tf.render.entity.EntityRendererAlt.func_78471_a(EntityRendererAlt.java:35)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Skullcrusher1027'/18, l='MpServer', x=-423.50, y=5.62, z=1717.50]]
    Chunk stats: MultiplayerChunkCache: 110, 110
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-430,4,1713), Chunk: (at 2,0,1 in -27,107; contains blocks -432,0,1712 to -417,255,1727), Region: (-1,3; contains chunks -32,96 to -1,127, blocks -512,0,1536 to -1,255,2047)
    Level time: 19 game time, 19 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityClientPlayerMP['Skullcrusher1027'/18, l='MpServer', x=-423.50, y=5.62, z=1717.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 193689992 bytes (184 MB) / 417923072 bytes (398 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 14 mods loaded, 14 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   PlayerAPI{1.4} [Player API](minecraft.jar) 
    UCHIJAAAA   RenderPlayerAPI{1.0} [Render Player API](minecraft.jar) 
    UCHIJAAAA   SmartCore{1.0} [Smart Core](minecraft.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) 
    UCHIJAAAA   mcheli{0.10.8} [MC Helicopter](mcheli) 
    UCHIJAAAA   Morph{0.9.0} [Morph](Morph-Beta-0.9.0.jar) 
    UCHIJAAAA   MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCHIJAAAA   SmartMoving{15.1} [Smart Moving](SmartMoving-1.7.10-15.1.jar) 
    UCHIJAAAA   SmartRender{2.0} [Smart Render](SmartRender-1.7.10-2.0.jar) 
    UCHIJAAAA   transformers{0.4.4} [Transformers Mod](Transformers-1.7.10-0.4.4.zip) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.62' Renderer: 'GeForce GT 610/PCIe/SSE2'
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.62, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Gegy** [comment]
This mod is not compatible with Smart Moving, Smart Render or RenderPlayerAPI

**Comment by DeadAtNooN** [comment]
ok thanks  you
