### ISSUE TITLE
No more entity indicies left - Crash

### ISSUE THREAD

**Issue by mogeli** [FiskFille/TransformersMod#155]
I am playing a modpack that I created myself, however, when I try to launch to gives the crash log stating " No more entity indicies left" and this is resolved by removing your mod; However, I also believe that this mod is not entirely to blame. But, my reason for putting it here is that this is the only mod that shows as an error. I have tried to take out I have took out a few mods the only other mod that prevented the crash was OreSpawn. I hope this can be resolved and I will post the log below.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 26/02/16 21:51
Description: Initializing game

java.lang.RuntimeException: No more entity indicies left
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 217791152 bytes (207 MB) / 519110656 bytes (495 MB) up to 6429081600 bytes (6131 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 69 mods loaded, 69 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCH ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCH OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) 
    UCH lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) 
    UCH FLabsBF{4.3} [Better Furnaces]([1.7.10]Better_Furnaces_V4.3.jar) 
    UCH AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCH Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) 
    UCH BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCH AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCH BrandonsCore{1.0.0.11} [Brandon's Core](BrandonsCore-1.0.0.11.jar) 
    UCH CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCH ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCH ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCH DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCH DraconicEvolution{1.0.2-snapshot_9} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCH HerobrineFamPack{1.7.10} [HerobrineFamPack](FamiliarsHerobrineFamPack-1.7.10.jar) 
    UCH McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCH ganyssurface{1.12.7} [Gany's Surface](Ganys Surface-1.12.7.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
    UCH guideapi{1.7.10-1.0.1-23} [Guide-API](Guide-API-1.7.10-1.0.1-23.jar) 
    UCH InventoryPets{1.3.91} [Inventory Pets](inventorypets-1.7.10-1.3.91-universal.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCH journeymap{5.1.4} [JourneyMap](journeymap-1.7.10-5.1.4-unlimited.jar) 
    UCH legends{1.4} [Legends Mod](Legends Core-1.4.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCH Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCH Morpheus{1.7.10-1.6.21} [Morpheus](Morpheus-1.7.10-1.6.21.jar) 
    UCH MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCH neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCH OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCH OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCH OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) 
    UCH PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCH JotatosPracticalities{0.6.2} [Practicalities](practicalities-1.7.10-0.6.2.jar) 
    UCH quantumflux{1.7.10-1.3.4} [QuantumFlux](QuantumFlux-1.7.10-1.3.4.jar) 
    UCH RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCH StorageDrawers{1.7.10-1.9.2} [Storage Drawers](StorageDrawers-1.7.10-1.9.2.jar) 
    UCH sus{4.3.2} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.3.2.jar) 
    UCH susaddon{4.3.2} [Superheroes Unlimited Mod (Part 2)](Superheroes Unlimited Mod-1.7.10-4.3.2.jar) 
    UCH Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCH thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCH ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCH TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCE transformers{${version}} [Transformers Mod](Transformers-1.7.10-0.5.10.jar) 
    UCH VeinMiner{0.31.3_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.31.3.unknown.jar) 
    UCH VeinMinerModSupport{0.31.3_build.unknown} [Mod Support](VeinMiner-1.7.10_0.31.3.unknown.jar) 
    UCH WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCH warpbook{2.0.null} [Warp Book](warpbook-1.7.10_2.0.36.jar) 
    UCH Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
    UCH ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13417 Compatibility Profile Context 15.301.1201.0' Renderer: 'AMD Radeon (TM) R9 390 Series'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon (TM) R9 390 Series GL version 4.5.13417 Compatibility Profile Context 15.301.1201.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [faithful32pack.zip, pvptexturepack_25_betterskies.zip]
Current Language: English (UK)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by runescapejon** [comment]
Having SuperHeroes unlimted and Orespawn together with Transformers mod it says java.lang.RuntimeException: No more entity indicies left meaning by there are no Entities ID left you would have to remove one of the mods i listed above :/ well it sucks unless one of the mods reduce there entities id's
