### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [FiskFille/TransformersMod#158]
So I got a crash. And I was wondering what mods i need to remove to fix this.

---- Minecraft Crash Report ----
// My bad.

Time: 3/27/16 9:06 PM
Description: Initializing game

java.lang.RuntimeException: No more entity indicies left
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 585259504 bytes (558 MB) / 1721761792 bytes (1642 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D3 73 mods loaded, 73 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCH Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCH OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
    UCH bspkrsCore{6.16.sincommand} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.sincommand.jar) 
    UCH ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) 
    UCH StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) 
    UCH AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCH Backpack{2.0.1} [Backpack](Backpacks-Mod.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles.jar) 
    UCH BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCH BuildCraft|Core{7.1.16} [BuildCraft](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Builders{7.1.16} [BC Builders](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Transport{7.1.16} [BC Transport](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Energy{7.1.16} [BC Energy](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Silicon{7.1.16} [BC Silicon](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Robotics{7.1.16} [BC Robotics](buildcraft-7.1.16.jar) 
    UCH BuildCraft|Factory{7.1.16} [BC Factory](buildcraft-7.1.16.jar) 
    UCH CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenters-Blocks-Mod-1.7.10.zip) 
    UCH ChickenBones{1.0} [The Chicken Bones Mod: You can pick up chicks!](ChickenBones-1.7.10-J7.jar) 
    UCH ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCH EE3{0.3.507} [Equivalent Exchange 3](Equivalent Exchange 3.jar) 
    UCH chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCH endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCH ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.3-112.jar) 
    UCH ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UCH iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCH GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
    UCH Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCH headcrumbs{1.7.4} [Headcrumbs](Headcrumbs-1.7.4.jar) 
    UCH InventoryPets{1.1.2a} [Inventory Pets](Inventory Pets.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCH IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCH jaff{1.4.1_for_1.7.10} [Just a Few Fish](JustAFewFish-1.4.1_for_1.7.10.jar) 
    UCH legends{1.4} [Legends Mod](Legends Core-1.4.jar) 
    UCH ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCH LogisticsPipes{0.9.3.103} [Logistics Pipes](logisticspipes-0.9.3.103.jar) 
    UCH lootplusplus{0.22_for_1.7} [Loot++](Loot++-0.22_for_1.7.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCH MapWriter{2.1.8} [MapWriter](MapWriter-1.7.10-2.1.10.jar) 
    UCH MobProperties{0.4.0} [Mob Properties](Mob Properties.jar) 
    UCH morehealth{6.0} [More Health Forge](More-Health-Enhanced-Mod-1.7.10.zip) 
    UCH mrnobody_morecommands{1.6} [More Commands](MoreCommands-1.7.10-1.6.jar) 
    UCH Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCH MutantCreatures{1.4.9} [Mutant Creatures](MutantCreatures-1.7.10-1.4.9.jar) 
    UCH NEIAddons{1.12.10.33} [NEI Addons](NEI Addons- Ex Nihilo.jar) 
    UCH NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](NEI Addons- Ex Nihilo.jar) 
    UCH NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](NEI Addons- Ex Nihilo.jar) 
    UCH NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](NEI Addons- Ex Nihilo.jar) 
    UCH NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](NEI Addons- Ex Nihilo.jar) 
    UCH NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](NEI Addons- Ex Nihilo.jar) 
    UCH OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UCH OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
    UCH OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) 
    UCH PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
    UCH Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCH SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](Soul Shards- The Old Ways.jar) 
    UCH sus{4.3.2} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.3.2.jar) 
    UCH susaddon{4.3.2} [Superheroes Unlimited Mod (Part 2)](Superheroes Unlimited Mod-1.7.10-4.3.2.jar) 
    UCH TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCH ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCE transformers{${version}} [Transformers Mod](Transformers-1.7.10-0.5.3.jar) 
    UCH WailaHarvestability{1.1.6} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.6.jar) 
    UCH wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.2.0-23.jar) 
    UCH worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCH lucky{5.1.0} [Lucky Block](z[1-7-10]_Lucky_Block_v5-1-0.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.3-112
    ThermalExpansion: -[1.7.10]4.1.2-240
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Faithful Revenge V1.15.4.zip, Connected Glass 32x, Lucky Block Spiral v1.1-1.7.10]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D3
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 364.51
OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
```

**Comment by ghost** [comment]
Also. When removing the mod. The game launches fine.

**Comment by Gegy** [comment]
You have too many mods that are adding new entities, there are a limited amount of entity types Minecraft can handle and with all the mods you have, you are exceeding that limit. You'll have to remove some mods, unfortunately there is nothing we can do about this.

**Comment by ghost** [comment]
Any mods i should remove?

**Comment by FiskFille** [comment]
OreSpawn and Superheroes Unlimited are two common culprits.

**Comment by CaedynB** [comment]
Hmm. Would there be a possible way to not have to remove any mods?

**Comment by ghost** [comment]
Thanks. I removed Superheroes Unlimited and put in Project Superhuman and then the transformers mod worked. Thanks!

**Comment by ghost** [comment]
Also. Is there any way I can override the hand when wearing the transformers armor so i see my normal hand?

**Comment by Gegy** [comment]
The mod is incompatible with Optifine, so installing Optifine disables the custom arm.

**Comment by ghost** [comment]
Thats odd. I have Optifine installed.

**Comment by Gegy** [comment]
Oh, maybe someone fixed the incompatibilty.

**Comment by FiskFille** [comment]
_Whistles_

**Comment by ghost** [comment]
:P FiskFille, for your next update, would you mind adding an option into the config for disabling and enabling the custom hand?
