### ISSUE TITLE
Well. CRASH

### ISSUE THREAD

**Issue by ghost** [FiskFille/TransformersMod#159]
My second thread on this. Anyway. My game crashes when I install the mod. Whenever the mod is removed. It works fine. Someone replied on my last issue stating that I need to remove some mods. Now. I'd like to know what mods I should remove. 

Here's the crash
 ---- Minecraft Crash Report ----
// My bad.

Time: 3/27/16 9:06 PM
Description: Initializing game

java.lang.RuntimeException: No more entity indicies left
at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:17)
at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 585259504 bytes (558 MB) / 1721761792 bytes (1642 MB) up to 3817865216 bytes (3641 MB)
JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D3 73 mods loaded, 73 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH mcp{9.05} Minecraft Coder Pack 
UCH FML{7.10.99.99} Forge Mod Loader 
UCH Forge{10.13.4.1558} Minecraft Forge 
UCH appliedenergistics2-core{rv2-stable-10} AppliedEnergistics2 Core 
UCH CodeChickenCore{1.0.7.47} CodeChicken Core 
UCH NotEnoughItems{1.0.5.120} Not Enough Items 
UCH OpenModsCore{0.9.1} OpenModsCore 
UCH {000} CoFH ASM 
UCH battlegear2{1.7.10} Mine & Blade Battlegear 2 - Bullseye 
UCH bspkrsCore{6.16.sincommand} bspkrsCore 
UCH ArmorStatusHUD{1.28} ArmorStatusHUD 
UCH StatusEffectHUD{1.27} StatusEffectHUD 
UCH AnimationAPI{1.2.4} AnimationAPI 
UCH appliedenergistics2{rv2-stable-10} Applied Energistics 2 
UCH Backpack{2.0.1} Backpack 
UCH Baubles{1.0.1.10} Baubles 
UCH BiblioCraft{1.10.5} BiblioCraft 
UCH CoFHCore{1.7.10R3.1.2} CoFH Core 
UCH BuildCraft|Core{7.1.16} BuildCraft 
UCH BuildCraft|Builders{7.1.16} BC Builders 
UCH BuildCraft|Transport{7.1.16} BC Transport 
UCH BuildCraft|Energy{7.1.16} BC Energy 
UCH BuildCraft|Silicon{7.1.16} BC Silicon 
UCH BuildCraft|Robotics{7.1.16} BC Robotics 
UCH BuildCraft|Factory{7.1.16} BC Factory 
UCH CarpentersBlocks{3.2.5} Carpenter's Blocks 
UCH ChickenBones{1.0} The Chicken Bones Mod: You can pick up chicks! 
UCH ChickenChunks{1.3.4.19} ChickenChunks 
UCH EE3{0.3.507} Equivalent Exchange 3 
UCH chisel{2.5.1.44} Chisel 2 
UCH endercore{1.7.10-0.2.0.31_beta} EnderCore 
UCH ThermalFoundation{1.7.10R1.2.3} Thermal Foundation 
UCH ExtraUtilities{1.2.12} Extra Utilities 
UCH iChunUtil{4.2.2} iChunUtil 
UCH GraviGun{4.0.0-beta} GraviGun 
UCH Hats{4.0.1} Hats 
UCH headcrumbs{1.7.4} Headcrumbs 
UCH InventoryPets{1.1.2a} Inventory Pets 
UCH inventorytweaks{1.59-dev-152-cf6e263} Inventory Tweaks 
UCH IronChest{6.0.62.742} Iron Chest 
UCH jaff{1.4.1_for_1.7.10} Just a Few Fish 
UCH legends{1.4} Legends Mod 
UCH ThermalExpansion{1.7.10R4.1.2} Thermal Expansion 
UCH LogisticsPipes{0.9.3.103} Logistics Pipes 
UCH lootplusplus{0.22_for_1.7} Loot++ 
UCH Mantle{1.7.10-0.3.2.jenkins191} Mantle 
UCH MapWriter{2.1.8} MapWriter 
UCH MobProperties{0.4.0} Mob Properties 
UCH morehealth{6.0} More Health Forge 
UCH mrnobody_morecommands{1.6} More Commands 
UCH Morph{0.9.2} Morph 
UCH MutantCreatures{1.4.9} Mutant Creatures 
UCH NEIAddons{1.12.10.33} NEI Addons 
UCH NEIAddons|AppEng{1.12.10.33} NEI Addons: Applied Energistics 2 
UCH NEIAddons|Botany{1.12.10.33} NEI Addons: Botany 
UCH NEIAddons|Forestry{1.12.10.33} NEI Addons: Forestry 
UCH NEIAddons|CraftingTables{1.12.10.33} NEI Addons: Crafting Tables 
UCH NEIAddons|ExNihilo{1.12.10.33} NEI Addons: Ex Nihilo 
UCH OpenMods{0.9.1} OpenMods 
UCH OpenBlocks{1.5.1} OpenBlocks 
UCH OreSpawn{1.7.10.20.3} OreSpawn 
UCH PortalGun{4.0.0-beta-6} PortalGun 
UCH Waila{1.5.10} Waila 
UCH SSTOW{1.7.10-0.1-RC9-7} Soul Shards: The Old Ways 
UCH sus{4.3.2} Superheroes Unlimited Mod 
UCH susaddon{4.3.2} Superheroes Unlimited Mod (Part 2) 
UCH TConstruct{1.7.10-1.8.8.build988} Tinkers' Construct 
UCH ThermalDynamics{1.7.10R1.1.0} Thermal Dynamics 
UCE transformers{${version}} Transformers Mod 
UCH WailaHarvestability{1.1.6} Waila Harvestability 
UCH wailaplugins{MC1.7.10-0.2.0-23} WAILA Plugins 
UCH worldedit{6.0-beta-01} WorldEdit 
UCH lucky{5.1.0} Lucky Block 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 364.51' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
CoFHCore: -[1.7.10]3.1.2-325
ThermalFoundation: -[1.7.10]1.2.3-112
ThermalExpansion: -[1.7.10]4.1.2-240
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
TConstruct Environment: Environment healthy.
ThermalDynamics: -[1.7.10]1.1.0-161
Stencil buffer state: Function set: GL30, pool: forge, bits: 8
Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
LWJGL: 2.9.1
OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.51, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Faithful Revenge V1.15.4.zip, Connected Glass 32x, Lucky Block Spiral v1.1-1.7.10]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D3
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 364.51
OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8

Now. What to remove?

**Comment by CaedynB** [comment]
Disregard thread.
I didn't find a fix and every "Staff" member  is r00d

**Comment by Gegy** [comment]
What mod(s) you remove is up to you, remove mods that have entities until the error goes away. :)

**Comment by ghost** [comment]
Ah. Thank you.

**Comment by ghost** [comment]
Also. Is there any way I can override the hand when wearing the transformers armor so i see my normal hand?
