### ISSUE TITLE
CRASHED!

### ISSUE THREAD

**Issue by pikacrafter101** [FiskFille/TransformersMod#178]
Hello there, I'm pikacrafter101 :)
I was loading up the mod, when I got this crash.  Could you please help me fix this?
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/10/16 4:00 PM
Description: Initializing game

java.lang.RuntimeException: No more entity indicies left
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:13)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
    at fiskfille.tf.common.entity.TFEntities.registerEntity(TFEntities.java:34)
    at fiskfille.tf.common.entity.TFEntities.registerEntities(TFEntities.java:13)
    at fiskfille.tf.TransformersMod.preInit(TransformersMod.java:97)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 86866072 bytes (82 MB) / 343339008 bytes (327 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 22 mods loaded, 22 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCH Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCH CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) 
    UCH adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8c.jar) 
    UCH customnpcs{1.7.10d} [CustomNpcs](Custom-NPCs-Mod-1.7.10.jar) 
    UCH DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCH eplus{3.0.2-d} [Enchanting Plus](Enchanting-Plus-Mod-1.7.10.jar) 
    UCH EE3{0.3.0.547} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.0.547.jar) 
    UCH InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.7.10-1.4.8.1-universal.jar) 
    UCH IronChest{6.0.60.741} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) 
    UCH legends{1.6} [Legends Mod](Legends Core-1.6.jar) 
    UCH OreSpawn{1.7.10.20.3} [OreSpawn](Ore-Spawn-Mod-1.7.10.zip) 
    UCH SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
    UCH ironman{4.3.12} [Iron Man Armor Extension](Superheroes Unlimited Mod-1.7.10-4.3.12.jar) 
    UCH sus{4.3.12} [Superheroes Unlimited Mod](Superheroes Unlimited Mod-1.7.10-4.3.12.jar) 
    UCH susaddon{4.3.12} [Superheroes Unlimited Mod (Part 2)](Superheroes Unlimited Mod-1.7.10-4.3.12.jar) 
    UCE transformers{0.5.12} [Transformers Mod](TransformersMod-1.7.10-0.5.12.jar) 
    UCH VeinMiner{0.34.1_1.7.10-4d066f1} [Vein Miner](VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
    UCH VeinMinerModSupport{0.34.1_1.7.10-4d066f1} [Mod Support](VeinMiner-0.34.1-1.7.10r473+4d066f1.jar) 
    UCH pacman{1.0.8} [Killer Pacman](PacmanMod-1.0.8.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
    Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by runescapejon** [comment]
`No more entity indicies left`
having Orespawn and Transformer's and Superhero's mod is a bad mix your just going to crash this crash is basically saying that there is no more entitie's id's

**Comment by Gegy** [comment]
You will have to uninstall some mods that are adding lots of entities.
