### ISSUE TITLE
BUG!

### ISSUE THREAD

**Issue by lordyplays** [FiskFille/TransformersMod#238]
The game doesn't even load my world, even though I'm using forge 1.7.10. This is the details:
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.doesOreNameExist(Ljava/lang/String;)Z
Help! Is there anything else I have to have for this mod?
I also have this.
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 12/25/18 10:20 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.oredict.OreDictionary.doesOreNameExist(Ljava/lang/String;)Z
	at fiskfille.tf.common.recipe.TFRecipes.addMaterialCompression(TFRecipes.java:340)
	at fiskfille.tf.common.recipe.TFRecipes.register(TFRecipes.java:103)
	at fiskfille.tf.common.event.CommonEventHandler.onItemStitchPost(CommonEventHandler.java:272)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_83_CommonEventHandler_onItemStitchPost_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at fiskfille.tf.common.item.ItemHandler.load(ItemHandler.java:93)
	at fiskfille.tf.common.event.CommonEventHandler.onWorldLoad(CommonEventHandler.java:266)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_71_CommonEventHandler_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 231483032 bytes (220 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 15, allocated: 29, tallocated: 77
	FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.85.1232} [Forge Mod Loader] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.2.1232} [Minecraft Forge] (forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	legends{1.8.3} [Legends Mod] (Legends Core-1.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	sum{5.0.7} [Superheroes Unlimited Mod] (Superheroes Unlimited-1.7.10-5.0 Alpha 4.2 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	transformers{0.6.3} [Transformers Mod] (TransformersMod-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	transformersg1{1.1.1} [Transformers Mod G1 Edition] (TransformersG1-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by FiskFille** [comment]
You're using a very old version of Forge (1232). This mod requires 1558.
