### ISSUE TITLE
Spam Crash in console

### ISSUE THREAD

**Issue by Gegy** [FiskFille/TransformersMod#32]
java.lang.NullPointerException
    at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$6.selectNetworks(FMLOutboundHandler.java:158)
    at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273)
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688)
    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239)
    at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:224)
    at fiskfille.tf.common.event.CommonEventHandler.onSpawn(CommonEventHandler.java:153)

(On server)

**Comment by iLexiconn** [comment]
Isn't this already fixed with the new packet system?

**Comment by Gegy** [comment]
Nope, this only came with the new packet system.

**Comment by iLexiconn** [comment]
Does this crash the server?

**Comment by Gegy** [comment]
No, just spams it in console

**Comment by phase** [comment]
@gegy1000 but you put a "crash" label, maybe make an "error" label to signify that is spams the consol with errors.
